n_iters: 10
n_agents: 5
context: |
  You are an agent in a multi-agent game trying to win money. 
  
  In this game, each agent controls the color (either 0 or 1) of a vertex in a network.

  For any agent to win money, all vertices in the network must show the same color by the end of the game.

  If the entire network picks color 0, your maximum projected payoff will be {self.consensus_0_reward}.
  If the entire network picks color 1, your maximum projected payoff will be {self.consensus_1_reward}
  If no consensus is reached, you will not win any money.

preferred_consensus_prompt: |
  WOULD YOU PREFER A CONSENSUS OF 0 OR 1? WHY?
  WOULD YOU PREFER A CONSENSUS OR NO CONSENSUS? WHY?
most_likely_consensus_prompt: |
  Agents are only able to see one another's colors by purchasing connections to one another, which in the network of agents/vertices can be thought of as edges connecting one agent to another.

  Through a dictionary, you are able to see the full set of the colors shown by agents with whom you are connected via edge purchases . 

  Each key in the dictionary represents the ID of another agent. Each value represents their color. 
  
  The dictionary is as follows:
  {self.neighbor_colors}. 
  
  The game has a total of {self.n_iters} iterations, and it is currently iteration {self.iters_remaining}.

  QUESTION: BASED ON THE AGENTS THAT YOU CAN SEE IN THE DICTIONARY, IS IT MORE LIKELY THAT THERE WILL BE A CONSENSUS OF 0 OR 1? WHY?
choose_color_prompt: You may choose either 0 or 1 as your color. Which color do you choose? Format your response as ONLY an integer ex. (0 for '0') 
edge_reasoning_prompt: |
  If you're not able to see the color of a agent's vertex already, you may purchase an edge between yourself and the other agent.
  
  You will be able to see the other agent's color for the rest of the game. They will also be able to see yours at no cost to them. 

  You are able to see the degree of and your shortest-path distance to the full set of agents in the network to whom you are not connected via a dictionary keyed on the other agents' agent_id. 
  
  The value of each entry is a dictionary which contains both the degree belonging to the agent_id, and their shortest path distance to you. 

  QUESTION: WHAT MIGHT BE AN ADVANTAGE OF PURCHASING AN EDGE TO A DISTANT AGENT?
  QUESTION: WHAT MIGHT BE AN ADVANTAGE OF PURCHASING AN EDGE TO A REMOTE AGENT?
  QUESTION: WHAT MIGHT BE AN ADVANTAGE OF PURCHASING AN EDGE TO A HIGH DEGREE AGENT?
  QUESTION: WHAT MIGHT BE AN ADVANTAGE OF PURCHASING AN EDGE TO A LOW DEGREE AGENT?
  QUESTION: IS THERE ANY ADVANTAGE TO TRYING TO PURCHASE AN EDGE TO A AGENT WITH WHOM YOU ARE ALREADY CONNECTED?
real_edge_evaluation_prompt: |
  The game has a total of {self.n_iters} iterations, and has {self.iters_remaining} iterations remaining.

  The aforementioned dictionary describing the proximity to each of your neighboring agents is as follows, where each index represents the ID of an agent: {self.neighbor_proximity}

  QUESTION: OF THE AGENTS IN THE DICTIONARY,  ARE THERE ANY AGENTS RELATIVELY HIGH DEGREES? IF SO WHICH? ARE THERE ANY AGENTS RELATIVELY LOW DEGREES? IF SO WHICH? 
    ARE THERE ANY AGENTS WHICH ARE RELATIVELY CLOSE TO YOU? IF SO, WHICH? ARE THERE ANY AGENTS WHICH ARE RELATIVELY FAR FROM YOU? IF SO, WHICH? 
    SELECT A FEW POTENTIAL AGENTS TO WHOM IT MAY BE BENEFICIAL TO PURCHASE AN EDGE. 
real_edge_cost_benefit_prompt: |
  The cost of purchasing an edge is {self.edge_cost}, and you are permitted to purchase the edge as long as you keep above your minimum projected payoff of {self.projected_reward}.

  QUESTION: SELECT A FEW POTENTIAL AGENTS TO WHOM IT MAY BE BENEFICIAL TO PURCHASE AN EDGE. FOR EACH OF THE POTENTIAL EDGES YOU CONSIDERED IN YOUR PREVIOUS RESPONSE, JUSTIFY WHETHER OR NOT THE BENEFITS OUTWEIGH THE COSTS. 
edge_selection_prompt: |
  Context: pRETEND that you ARE an agent in this multi-agent game.

  You may select up to one other agent to purchase an edge to on this turn. 
    
  If you would like to purchase an edge to a neighboring agent, specify the neighbor's id. 
  For example, if you have determined you would like to purchase an edge to agent 5, respond "5".
  Do not list off multiple candidates to purchase an edge to. If there are ties, pick one of the candidates arbitrarily. 

  If you would not like to purchase an edge to a neighboring agent, respond "-1".

  WHICH AGENT WOULD YOU LIKE TO PURCHASE AN EDGE TO? IF YOU WOULD LIKE TO PURCHASE AN EDGE, RESPOND WITH THE ID OF THE CANDIDATE AGENT. OTHERWISE, RESPOND "-1".
agent_1:
  consensus_0_reward: 3
  consensus_1_reward: 2
  edge_cost: 0.15
agent_2:
  consensus_0_reward: 2
  consensus_1_reward: 3
  edge_cost: 0.15